add onbootstrapinit property
krakenjs/kraken-js pull request #514
Opened 2019-11-26 04:40 UTC by kumarrishav

moving the implementation details from #513

2019-11-26 20:13 UTC, kumarrishav commented
@tlivings @aheckmann @grawk @shaunwarman @gabrielcsapo review?

2019-11-26 20:24 UTC, sumeetkakkar commented on lib/bootstrap.js
> +    const onbootstrapinit = options.onbootstrapinit;
My understanding is that this is invoked when kraken is mounted in an express app and express app instance is available to pass down the callback function. Thoughts on calling this as `onkrakenmount` or `onmount`?

2019-11-26 22:34 UTC, grawk requested changes
No issues with the code change. Would just recommend to remove node 6 from the travis config.

2019-11-26 22:34 UTC, grawk commented on .travis.yml
> +  - "10"
since you're cleaning up, is there a reason not to remove "6"?

2019-12-09 23:12 UTC, sumeetkakkar commented on test/kraken.js
> +                const serverListen = app.listen;
I think we should just assert that the app is an express instance.

2019-12-12 22:16 UTC, sumeetkakkar commented on test/kraken.js
> +                t.ok(app.mountpath, 'app instance exist');
I think app would be a `function`. We can assert that as well.

2020-01-17 01:24 UTC, grawk approved these changes

2020-01-17 01:52 UTC, sumeetkakkar approved these changes

2020-01-21 22:31 UTC, snowinferno commented on index.js
> +        const onkrakenmount = options.onkrakenmount;
Please use camel case for options and variables. This should be `onKrakenMount`

2020-01-28 23:34 UTC, Greg-Wilburn approved these changes

2020-01-28 23:59 UTC, merged